# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import management_pb2 as management__pb2


class ManagementServerStub(object):
  """service, encode a plain text 
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/management.ManagementServer/SayHello',
        request_serializer=management__pb2.HelloRequest.SerializeToString,
        response_deserializer=management__pb2.HelloReply.FromString,
        )
    self.ReportContainerFailure = channel.unary_unary(
        '/management.ManagementServer/ReportContainerFailure',
        request_serializer=management__pb2.FailureInfo.SerializeToString,
        response_deserializer=management__pb2.FailureResponse.FromString,
        )
    self.AddModel = channel.unary_unary(
        '/management.ManagementServer/AddModel',
        request_serializer=management__pb2.ModelInfo.SerializeToString,
        response_deserializer=management__pb2.Response.FromString,
        )
    self.AddModelContainer = channel.unary_unary(
        '/management.ManagementServer/AddModelContainer',
        request_serializer=management__pb2.ModelContainerInfo.SerializeToString,
        response_deserializer=management__pb2.Response.FromString,
        )
    self.AddProxyContainer = channel.unary_unary(
        '/management.ManagementServer/AddProxyContainer',
        request_serializer=management__pb2.ProxyContainerInfo.SerializeToString,
        response_deserializer=management__pb2.Response.FromString,
        )
    self.AddDAG = channel.unary_unary(
        '/management.ManagementServer/AddDAG',
        request_serializer=management__pb2.DAGInfo.SerializeToString,
        response_deserializer=management__pb2.Response.FromString,
        )
    self.AddRuntimeDAG = channel.unary_unary(
        '/management.ManagementServer/AddRuntimeDAG',
        request_serializer=management__pb2.RuntimeDAGInfo.SerializeToString,
        response_deserializer=management__pb2.Response.FromString,
        )
    self.AddApp = channel.unary_unary(
        '/management.ManagementServer/AddApp',
        request_serializer=management__pb2.AppInfo.SerializeToString,
        response_deserializer=management__pb2.Response.FromString,
        )
    self.AddAppDAGLink = channel.unary_unary(
        '/management.ManagementServer/AddAppDAGLink',
        request_serializer=management__pb2.LinkInfo.SerializeToString,
        response_deserializer=management__pb2.Response.FromString,
        )
    self.UpdateRuntimeDAG = channel.unary_unary(
        '/management.ManagementServer/UpdateRuntimeDAG',
        request_serializer=management__pb2.RuntimeDAGInfo.SerializeToString,
        response_deserializer=management__pb2.Response.FromString,
        )
    self.GetModelByName = channel.unary_unary(
        '/management.ManagementServer/GetModelByName',
        request_serializer=management__pb2.ModelInfo.SerializeToString,
        response_deserializer=management__pb2.ModelInfo.FromString,
        )
    self.GetAllModel = channel.unary_unary(
        '/management.ManagementServer/GetAllModel',
        request_serializer=management__pb2.Request.SerializeToString,
        response_deserializer=management__pb2.ModelInfoList.FromString,
        )
    self.GetRuntimeDAG = channel.unary_unary(
        '/management.ManagementServer/GetRuntimeDAG',
        request_serializer=management__pb2.RuntimeDAGInfo.SerializeToString,
        response_deserializer=management__pb2.RuntimeDAGInfo.FromString,
        )


class ManagementServerServicer(object):
  """service, encode a plain text 
  """

  def SayHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReportContainerFailure(self, request, context):
    """////////////////////////////////////////////////////////////////
    Failure Daemon
    ////////////////////////////////////////////////////////////////

    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddModel(self, request, context):
    """////////////////////////////////////////////////////////////////
    Management Server
    ////////////////////////////////////////////////////////////////

    SET
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddModelContainer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddProxyContainer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddDAG(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddRuntimeDAG(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddApp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddAppDAGLink(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateRuntimeDAG(self, request, context):
    """Recoverey

    rpc StartUpdateRuntimeDAG (RuntimeDAGInfo) returns (RuntimeDAGInfo) {}
    rpc FinishUpdateRuntimeDAG (RuntimeDAGInfo) returns (RuntimeDAGInfo) {}
    rpc DropUpdateRuntimeEDAG (RuntimeDAGInfo) returns (RuntimeDAGInfo) {}

    UPDATE

    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetModelByName(self, request, context):
    """GET

    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAllModel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRuntimeDAG(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ManagementServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=management__pb2.HelloRequest.FromString,
          response_serializer=management__pb2.HelloReply.SerializeToString,
      ),
      'ReportContainerFailure': grpc.unary_unary_rpc_method_handler(
          servicer.ReportContainerFailure,
          request_deserializer=management__pb2.FailureInfo.FromString,
          response_serializer=management__pb2.FailureResponse.SerializeToString,
      ),
      'AddModel': grpc.unary_unary_rpc_method_handler(
          servicer.AddModel,
          request_deserializer=management__pb2.ModelInfo.FromString,
          response_serializer=management__pb2.Response.SerializeToString,
      ),
      'AddModelContainer': grpc.unary_unary_rpc_method_handler(
          servicer.AddModelContainer,
          request_deserializer=management__pb2.ModelContainerInfo.FromString,
          response_serializer=management__pb2.Response.SerializeToString,
      ),
      'AddProxyContainer': grpc.unary_unary_rpc_method_handler(
          servicer.AddProxyContainer,
          request_deserializer=management__pb2.ProxyContainerInfo.FromString,
          response_serializer=management__pb2.Response.SerializeToString,
      ),
      'AddDAG': grpc.unary_unary_rpc_method_handler(
          servicer.AddDAG,
          request_deserializer=management__pb2.DAGInfo.FromString,
          response_serializer=management__pb2.Response.SerializeToString,
      ),
      'AddRuntimeDAG': grpc.unary_unary_rpc_method_handler(
          servicer.AddRuntimeDAG,
          request_deserializer=management__pb2.RuntimeDAGInfo.FromString,
          response_serializer=management__pb2.Response.SerializeToString,
      ),
      'AddApp': grpc.unary_unary_rpc_method_handler(
          servicer.AddApp,
          request_deserializer=management__pb2.AppInfo.FromString,
          response_serializer=management__pb2.Response.SerializeToString,
      ),
      'AddAppDAGLink': grpc.unary_unary_rpc_method_handler(
          servicer.AddAppDAGLink,
          request_deserializer=management__pb2.LinkInfo.FromString,
          response_serializer=management__pb2.Response.SerializeToString,
      ),
      'UpdateRuntimeDAG': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateRuntimeDAG,
          request_deserializer=management__pb2.RuntimeDAGInfo.FromString,
          response_serializer=management__pb2.Response.SerializeToString,
      ),
      'GetModelByName': grpc.unary_unary_rpc_method_handler(
          servicer.GetModelByName,
          request_deserializer=management__pb2.ModelInfo.FromString,
          response_serializer=management__pb2.ModelInfo.SerializeToString,
      ),
      'GetAllModel': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllModel,
          request_deserializer=management__pb2.Request.FromString,
          response_serializer=management__pb2.ModelInfoList.SerializeToString,
      ),
      'GetRuntimeDAG': grpc.unary_unary_rpc_method_handler(
          servicer.GetRuntimeDAG,
          request_deserializer=management__pb2.RuntimeDAGInfo.FromString,
          response_serializer=management__pb2.RuntimeDAGInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'management.ManagementServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
